apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    keyvaultName: "team1-dh-vault"
    objects:  |
      array:
        - |
          objectName: sql-server
          objectAlias: SQL_SERVER
          objectType: secret
        - |
          objectName: sql-user
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: sql-password
          objectAlias: SQL_PASSWORD
          objectType: secret
    resourceGroup: "teamresources"
    subscriptionId: "0e5dfc5b-fefb-4800-8f8e-9f9eba6ac6fd"
    tenantId: "c8c6e8c1-945c-4691-8820-e322e2c11668"