apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-provider
  namespace: api-ns
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: SQLSERVER                           # data field to populate
      objectName: SQL_SERVER
    - key: SQLDBNAME                           # data field to populate
      objectName: SQL_DBNAME
    - key: SQLUSER                           # data field to populate
      objectName: SQL_USER
    - key: SQLPASSWORD                           # data field to populate
      objectName: SQL_PASSWORD                       # name of the mounted content to sync. this could be the object name or the object alias
    secretName: sqlsecret                     # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls